addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.3.6")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "1.6.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.dwijnand"     % "sbt-dynver"           % "4.0.0")
